# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IIGTYSrcqF8WR03Feyl7yrMWdqEmBT_t
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#importing the libraries

dataset = pd.read_csv('Salary_Data.csv')
dataset
#reading the dataset

#performing some actions
dataset.shape

dataset.info

dataset[3:]
#displays rows from 3 to end

dataset[:3]
#shows data from start to n-1 that is till 2

dataset.head()
#prints first five element of the dataset

dataset.tail()
#prints the last five elements of the datset

x = dataset.iloc[:,:1].values
x
#fetching the years of experince column

y = dataset.iloc[:,1].values
y
#fetching the salary of the dataset

#spliting the dataset to train and testing on it
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 1/3 , random_state = 0)

from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(x_train , y_train)

y_pred = regressor.predict(x_test)

#plotting the graph
plt.scatter(x_test,y_test,color = 'red')
plt.plot(x_train , regressor.predict(x_train))
plt.show()

